spring:
  profiles:
    include: oauth, local, aws
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
cloud:
  aws:
    s3:
      bucket: s3-spinoff
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true