spring:
  profiles:
    include: oauth, local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        default_batch_fetch_size: 1000